[package]
name = "webservice"
version = "0.1.0"
edition = "2021"
default-run = "test-ocr"

[dependencies]
rdev = "0.5.3"
scrap = "0.5.0"
image = "0.25.2"
regex = "1.11.0"
enigo = "0.2.1"

[[bin]]
name = "test-ocr"